categories:
- Synthetic Biology
description: Calculate the formation energy of chemical species and the Gibbs free
  energy of their reactions and pathways in an SBML
long_description: 'Calculate the formation energy of chemical species either using
  an internal database or estimate it by decomposing them using the component contribution
  (https://gitlab.com/elad.noor/component-contribution) method. Thereafter this tool
  predicts the Gibbs free energy of reactions and of the whole heterologous pathway
  by combining the formation energy of each individual compound. Source code may be
  found at the following location: https://github.com/brsynth/rptools/tree/master/rptools/rpthermo'
name: rpthermo
owner: tduigou
