name: cloning_simulation
owner: tduigou
categories:
  - Systems Biology
  - Synthetic Biology
description: A cloning simulator for synthetic biology.
long_description: Enables rapid and accurate preparation of DNA parts for modular cloning systems, such as Golden Gate Assembly
homepage_url: https://github.com/Edinburgh-Genome-Foundry/Examples/blob/master/templates/template1.ipynb
remote_repository_url: https://github.com/Edinburgh-Genome-Foundry/DnaCauldron/tree/master