categories:
- Synthetic Biology
description: Save data from gb files in DB 
long_description: 'Save data to SQL DB'
name: save_to_db
owner: tduigou
homepage_url: https://github.com/brsynth
remote_repository_url: https://github.com/brsynth