categories:
- Synthetic Biology
description: Visualize pathways from the RetroPath Suite
long_description: 'Visualize pathways from the RetroPath Suite. Source code may be
  found at the following location: https://github.com/brsynth/rptools/tree/master/rptools/rpviz'
name: rpviz
owner: tduigou
