categories:
- Synthetic Biology
description: Get DB as referance
long_description: 'get_DB_info interroge a SQL DB'
name: get_db_info
owner: tduigou
homepage_url: https://github.com/brsynth
remote_repository_url: https://github.com/brsynth