categories:
- Synthetic Biology
description: Rank heterologous pathways according to their global score
long_description: 'Rank heterologous pathways according to their global score. Source
  code may be found at the following location: https://github.com/brsynth/rptools/tree/master/rptools/rprank'
name: rpranker
owner: tduigou
