categories:
- Synthetic Biology
description: Performs enzyme selection from a reaction query.
long_description: 'Selenzy performs enzyme sequence selection from a reaction query.
  The tool can be queried using a reaction template such as the reaction rules in
  RetroRules(https://github.com/brsynth/RRParser). This feature makes this tool especially
  useful in combination with RetroPath2.0 (https://github.com/brsynth/RetroPath2-wrapper).
  Source code may be found at the following location: https://github.com/brsynth/selenzy-wrapper'
name: selenzy
owner: tduigou
homepage_url: https://github.com/brsynth/selenzy-wrapper
remote_repository_url: https://github.com/brsynth/selenzy-wrapper
