name: ReleaseSchedule

on:
  schedule:
    - cron: '0 0 * * 2'

jobs:

  Diff:
    runs-on: ubuntu-latest
    outputs:
      nb: ${{ steps.set-diff.outputs.nb }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: 'stable'
      - name: "Check diff"
        id: set-diff
        run: |
          nb=$(git diff --shortstat stable..origin/main | cut -f2 -d ' ')
          echo "Find diff: ${nb}"
          echo "nb=${nb}" >> "${GITHUB_OUTPUT}"

  Call:
    needs: [Diff]
    if: ${{ needs.Diff.outputs.nb > 0 }}
    uses: ./.github/workflows/release.yml
    secrets: inherit
