name: ReleaseSchedule

on:
  schedule:
    - cron: '0 0 * * 2'

jobs:

  Diff:
    runs-on: ubuntu-latest
    outputs:
      nb: ${{ steps.set-diff.outputs.nb }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: 'stable'
      - name: "Check diff"
        id: set-diff
        continue-on-error: true
        run: |
          git diff --quiet stable..origin/main
          nb=$?
          echo "Find diff: ${nb}"
          echo "nb=${nb}" >> "${GITHUB_OUTPUT}"

  Call:
    runs-on: ubuntu-latest
    needs: [Diff]
    if: ${{ needs.Diff.outputs.nb > 0 }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: 'Dispatch'
        uses: ./.github/workflows/release.yml
