name: Tests

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:

  list_tool:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'List repos'
        id: set-matrix
        run: echo "matrix=$(find tools -depth 1 -type d | jq -R -s -c 'split("\n")[:-1] | map(split("/")[-1])')" >> "${GITHUB_ENV}"

  test_tool:
    needs: list_tool
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list_tool.outputs.matrix) }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: master
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: recipes/workflow.yaml
          mamba-version: "*"
          channel-priority: true
          use-mamba: true
      - name: 'Prepare output'
        run: |
          mkdir -p log
      - name: 'Wrapper Lint'
        run: |
          planemo lint --urls --doi "${matrix.manifest}"
      - name: 'Shed lint'
        run: |
          ./scripts/shed_lint.py -i "{matrix.manifest}"
      - name: 'Test tool'
        run: |
          mkdir -p "log/${matrix.manifest}"
          planemo test \
            --biocontainers \
            --no_dependency_resolution \
            --no_conda_auto_init \
            --galaxy_source https://github.com/galaxyproject/galaxy \
            --galaxy_branch release_22.05 \
            --galaxy_python_version 3.7 \
            --test_timeout 900 \
            --job_output_files "log/${matrix.manifest}" \
            "${matrix.manifest}"
      - name: 'Prepare artefact'
        run: |
          zip -r -9 log.zip log
      - name: 'Upload Artifact Version'
        uses: actions/upload-artifact@v3
        with:
          name: log-artifact
          path: log.zip
